name: Output hello.txt Content

on:
  push:
    branches:
      - main

jobs:
  show-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display hello.txt content
        run: cat hello.txt